# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 12:37
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('paid_from', models.DateTimeField(null=True)),
                ('paid_until', models.DateTimeField(null=True)),
                ('payment_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('duration', models.IntegerField()),
                ('price_per_month', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.AddField(
            model_name='uservideosubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uservideosubscription',
            name='length_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.TextField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uservideosubscription',
            name='subscribed_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videolearner.SubscriptionType'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='videolearner.Subscription'),
        ),
    ]
