# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0004_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='description',
            field=models.TextField(default='Monthly'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
