# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0005_auto_20160819_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chain_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
