# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0008_auto_20160820_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='confirmation_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
