# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0009_auto_20160820_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='paid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paid_until',
            field=models.DateTimeField(),
        ),
    ]
