# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0010_auto_20160822_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([('email',)]),
        ),
    ]
