# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0012_auto_20160822_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfirmation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserConfirmation',
        ),
    ]
