# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0013_auto_20160823_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='length',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videolearner.Subscription'),
        ),
    ]
