# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 23:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0014_auto_20160823_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='month',
        ),
        migrations.AddField(
            model_name='userbadge',
            name='awarded_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 23, 23, 9, 422768, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
