# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0016_uservideo_credits_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='awarded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
