# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolearner', '0017_auto_20160824_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbadge',
            old_name='awarded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='userbadge',
            name='award_month',
            field=models.CharField(default='August 2016', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together=set([('user', 'award_month')]),
        ),
    ]
